### ISSUE TITLE
Unable to launch with ./runme

### ISSUE THREAD

**Issue by pquentin** [glyph/Pomodouroboros#72]
## Steps to reproduce the failure

I'm using Python 3.13.0 from Homebrew on macOS 15.1. I'm using `bash`. One minor reason for migrating from Linux to macOS was in fact, Pomodorouboros! All absolute paths were shortened to `/.../`.

```bash
$ python3 -m venv .venv
$ source .venv/bin/activate
$ pip install -r requirements.txt
...
Successfully installed altgraph-0.17.4 appdirs-1.4.4 attrs-24.2.0 automat-24.8.1 bcrypt-4.2.0 build-1.2.1 cffi-1.17.0 click-8.1.7 constantly-23.10.4 cryptography-43.0.1 cython-test-exception-raiser-1.0.2 datetype-2024.2.28 delocate-0.12.0 encrust-2024.9.3 fritter-0.0.9 h2-4.1.0 hpack-4.0.0 hyperframe-6.0.1 hyperlink-21.0.0 hypothesis-6.111.2 idna-3.8 incremental-24.7.2 macholib-1.16.3 modulegraph-0.19.6 mypy-1.5.1 mypy-extensions-1.0.0 mypy-zope-1.0.5 packaging-24.1 pip-tools-7.4.1 priority-1.3.0 py2app-0.28.8 pyasn1-0.6.0 pyasn1-modules-0.4.0 pycparser-2.22 pyhamcrest-2.1.0 pyobjc-core-10.3.1 pyobjc-framework-cfnetwork-10.3.1 pyobjc-framework-cocoa-10.3.1 pyobjc-framework-exceptionhandling-10.3.1 pyobjc-framework-usernotifications-10.3.1 pyopenssl-24.2.1 pyproject-hooks-1.1.0 pyserial-3.5 python-dateutil-2.9.0.post0 quickmacapp-2023.4.24 quickmachotkey-2023.11.17 service-identity-24.1.0 setuptools-70.3.0 six-1.16.0 sortedcontainers-2.4.0 twisted-24.7.0 types-python-dateutil-2.9.0.20240821 typing-extensions-4.12.2 tzdata-2024.1 ulid-py-1.1.0 wheel-0.44.0 wheel-filename-1.4.1 zope-event-5.0 zope-interface-7.0.3 zope-schema-7.0.1
$ ./runme
+ mypy ./src
Success: no issues found in 43 source files
+ rm -fr ./build ./dist
+ python setup.py py2app --alias
+ cat
running py2app
running build_py
creating build
creating build/bdist.macosx-14.0-arm64
creating build/bdist.macosx-14.0-arm64/lib
creating build/bdist.macosx-14.0-arm64/lib/pomodouroboros
copying src/pomodouroboros/__init__.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros
copying src/pomodouroboros/pommodel.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros
copying src/pomodouroboros/cli.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros
copying src/pomodouroboros/storage.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros
copying src/pomodouroboros/hasher.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros
creating build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/intentions_gui.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/multiple_choice.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/old_mac_gui.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/notifs.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/tab_order.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/__init__.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/text_fields.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/hudmulti.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos                                                                            copying src/pomodouroboros/macos/mac_dates.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/mac_gui.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/progress_hud.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/model_convert.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/sessions_gui.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/mac_utils.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
creating build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/sessions.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/color.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/boundaries.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/explanations.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/util.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/scoring.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/ideal.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/__init__.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/intervals.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/debugger.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/nexus.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/intention.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/storage.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/observables.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/schema.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
creating build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos/test
copying src/pomodouroboros/macos/test/__init__.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos/test
copying src/pomodouroboros/macos/test/test_nib_init.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos/test
creating build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model/test
copying src/pomodouroboros/model/test/test_model.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model/test
copying src/pomodouroboros/model/test/test_sessions.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model/test
copying src/pomodouroboros/model/test/__init__.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model/test
copying src/pomodouroboros/model/test/test_util.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model/test
copying src/pomodouroboros/model/test/test_observables.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model/test
creating /.../Pomodouroboros/build/bdist.macosx-14.0-arm64/python3.13-standalone
creating /.../Pomodouroboros/build/bdist.macosx-14.0-arm64/python3.13-standalone/app
creating /.../Pomodouroboros/build/bdist.macosx-14.0-arm64/python3.13-standalone/app/collect
creating /.../Pomodouroboros/build/bdist.macosx-14.0-arm64/python3.13-standalone/app/temp
creating /.../Pomodouroboros/dist
creating build/bdist.macosx-14.0-arm64/python3.13-standalone/app/lib-dynload
creating build/bdist.macosx-14.0-arm64/python3.13-standalone/app/Frameworks
/.../Pomodouroboros/dist/Pomodouroboros.app/Contents/MacOS/Pomodouroboros: replacing existing signature
/.../Pomodouroboros/dist/Pomodouroboros.app/Contents/MacOS/Pomodouroboros: signed app bundle with Mach-O thin (arm64) [im.glyph.and.this.is.pomodouroboros]
/.../Pomodouroboros/dist/Pomodouroboros.app: replacing existing signature
/.../Pomodouroboros/dist/Pomodouroboros.app: signed app bundle with Mach-O thin (arm64) [im.glyph.and.this.is.pomodouroboros]
Add paths for VENV /opt/homebrew/opt/python@3.13 False
*** creating application bundle: Pomodouroboros ***
Copy '/.../Pomodouroboros/.venv/lib/python3.13/site-packages/py2app/apptemplate/prebuilt/main-arm64' -> '/.../Pomodouroboros/dist/Pomodouroboros.app/C
ontents/MacOS/Pomodouroboros'
compile IBFiles/GoalListWindow.xib -> /.../Pomodouroboros/dist/Pomodouroboros.app/Contents/Resources/GoalListWindow.nib
compile IBFiles/IntentionEditor.xib -> /.../Pomodouroboros/dist/Pomodouroboros.app/Contents/Resources/IntentionEditor.nib
compile IBFiles/MainMenu.xib -> /.../Pomodouroboros/dist/Pomodouroboros.app/Contents/Resources/MainMenu.nib
compile IBFiles/ProgressHUD.xib -> /.../Pomodouroboros/dist/Pomodouroboros.app/Contents/Resources/ProgressHUD.nib
sign ['/.../Pomodouroboros/dist/Pomodouroboros.app/Contents/MacOS/Pomodouroboros']
Done!
+ rm -fr ./build
+ exec ./dist/Pomodouroboros.app/Contents/MacOS/Pomodouroboros
Traceback (most recent call last):
  File "/.../Pomodouroboros/dist/Pomodouroboros.app/Contents/Resources/__boot__.py", line 149, in <module>
    _run()
    ~~~~^^
  File "/.../Pomodouroboros/dist/Pomodouroboros.app/Contents/Resources/__boot__.py", line 143, in _run
    exec(compile(source, script, "exec"), globals(), globals())
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../Pomodouroboros/mac/Pomodouroboros.py", line 9, in <module>
    from pomodouroboros.macos.mac_gui import main
ModuleNotFoundError: No module named 'pomodouroboros'
2024-11-13 09:40:53.127 Pomodouroboros[6766:11699589] Launch error
2024-11-13 09:40:53.128 Pomodouroboros[6766:11699589] Launch error
See the py2app website for debugging launch issues
2024-11-13 09:40:53.582 Pomodouroboros[6766:11699589] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-13 09:40:53.582 Pomodouroboros[6766:11699589] +[IMKInputSession subclass]: chose IMKInputSession_Modern
```

Then I get the following prompt which takes me to https://py2app.readthedocs.io/en/latest/debugging.html if I click "Visit website".

<img width="257" alt="Screenshot 2024-11-13 at 09 41 05" src="https://github.com/user-attachments/assets/9b572785-9fa7-49ca-b02d-ac70e8230788">

## Steps to reproduce success

For some reason, when I type those two commands in my shell, however, Pomodouroboros launches properly:

```python
$ python setup.py py2app --alias | cat
running py2app
running build_py
creating build
creating build/bdist.macosx-14.0-arm64
creating build/bdist.macosx-14.0-arm64/lib
creating build/bdist.macosx-14.0-arm64/lib/pomodouroboros
copying src/pomodouroboros/__init__.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros
copying src/pomodouroboros/pommodel.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros
copying src/pomodouroboros/cli.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros
copying src/pomodouroboros/storage.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros
copying src/pomodouroboros/hasher.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros
creating build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/intentions_gui.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/multiple_choice.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/old_mac_gui.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/notifs.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/tab_order.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/__init__.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/text_fields.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/hudmulti.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/mac_dates.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/mac_gui.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/progress_hud.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/model_convert.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/sessions_gui.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
copying src/pomodouroboros/macos/mac_utils.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos
creating build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/sessions.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/color.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/boundaries.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/explanations.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/util.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/scoring.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/ideal.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/__init__.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/intervals.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/debugger.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/nexus.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/intention.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/storage.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/observables.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
copying src/pomodouroboros/model/schema.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model
creating build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos/test
copying src/pomodouroboros/macos/test/__init__.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos/test
copying src/pomodouroboros/macos/test/test_nib_init.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos/test
creating build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model/test
copying src/pomodouroboros/model/test/test_model.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model/test
copying src/pomodouroboros/model/test/test_sessions.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model/test
copying src/pomodouroboros/model/test/__init__.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model/test
copying src/pomodouroboros/model/test/test_util.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model/test
copying src/pomodouroboros/model/test/test_observables.py -> build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model/test
creating /.../Pomodouroboros/build/bdist.macosx-14.0-arm64/python3.13-standalone
creating /.../Pomodouroboros/build/bdist.macosx-14.0-arm64/python3.13-standalone/app
creating /.../Pomodouroboros/build/bdist.macosx-14.0-arm64/python3.13-standalone/app/collect
creating /.../Pomodouroboros/build/bdist.macosx-14.0-arm64/python3.13-standalone/app/temp
creating build/bdist.macosx-14.0-arm64/python3.13-standalone/app/lib-dynload
creating build/bdist.macosx-14.0-arm64/python3.13-standalone/app/Frameworks
/.../Pomodouroboros/dist/Pomodouroboros.app/Contents/MacOS/Pomodouroboros: replacing existing signature
/.../Pomodouroboros/dist/Pomodouroboros.app/Contents/MacOS/Pomodouroboros: signed app bundle with Mach-O thin (arm64) [im.glyph.and.this.is.pomodouroboros]
/.../Pomodouroboros/dist/Pomodouroboros.app: replacing existing signature
/.../Pomodouroboros/dist/Pomodouroboros.app: signed app bundle with Mach-O thin (arm64) [im.glyph.and.this.is.pomodouroboros]
Add paths for VENV /opt/homebrew/opt/python@3.13 False
*** creating application bundle: Pomodouroboros ***
Copy '/.../Pomodouroboros/.venv/lib/python3.13/site-packages/py2app/apptemplate/prebuilt/main-arm64' -> '/.../Pomodouroboros/dist/Pomodouroboros.app/Contents/MacOS/Pomodouroboros'
compile IBFiles/GoalListWindow.xib -> /.../Pomodouroboros/dist/Pomodouroboros.app/Contents/Resources/GoalListWindow.nib
compile IBFiles/IntentionEditor.xib -> /.../Pomodouroboros/dist/Pomodouroboros.app/Contents/Resources/IntentionEditor.nib
compile IBFiles/MainMenu.xib -> /.../Pomodouroboros/dist/Pomodouroboros.app/Contents/Resources/MainMenu.nib
compile IBFiles/ProgressHUD.xib -> /.../Pomodouroboros/dist/Pomodouroboros.app/Contents/Resources/ProgressHUD.nib
sign ['/.../Pomodouroboros/dist/Pomodouroboros.app/Contents/MacOS/Pomodouroboros']
Done!
$ exec ./dist/Pomodouroboros.app/Contents/MacOS/Pomodouroboros;
2024-11-13 09:51:52.387 Pomodouroboros[8216:11721816] kicking off first update
2024-11-13 09:51:52.387 Pomodouroboros[8216:11721816] updating
2024-11-13 09:51:52.389 Pomodouroboros[8216:11721816] refreshing after pomodoro start
2024-11-13 09:51:52.390 Pomodouroboros[8216:11721816] refreshing after intention status change
2024-11-13 09:51:52.523 Pomodouroboros[8216:11721816] refreshing list from listRefresher
2024-11-13 09:51:52.523 Pomodouroboros[8216:11721816] updating
2024-11-13 09:51:52.523 Pomodouroboros[8216:11721816] refreshing list from listRefresher
2024-11-13 09:51:52.523 Pomodouroboros[8216:11721816] updating
```

This is not a timing issue, adding `sleep 10` in `./runme` does not solve the problem. I just realized that the difference is that I'm not running `rm -rf build` locally. And commenting that out from the script indeed solves the issue. Here's the content of `build`:

```bash
$ ls -R build
bdist.macosx-14.0-arm64

build/bdist.macosx-14.0-arm64:
lib                   python3.13-standalone

build/bdist.macosx-14.0-arm64/lib:
pomodouroboros

build/bdist.macosx-14.0-arm64/lib/pomodouroboros:
__init__.py cli.py      hasher.py   macos       model       pommodel.py storage.py

build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos:
__init__.py        intentions_gui.py  mac_gui.py         model_convert.py   notifs.py          progress_hud.py    tab_order.py       text_fields.py
hudmulti.py        mac_dates.py       mac_utils.py       multiple_choice.py old_mac_gui.py     sessions_gui.py    test

build/bdist.macosx-14.0-arm64/lib/pomodouroboros/macos/test:
__init__.py      test_nib_init.py

build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model:
__init__.py     color.py        explanations.py intention.py    nexus.py        schema.py       sessions.py     test
boundaries.py   debugger.py     ideal.py        intervals.py    observables.py  scoring.py      storage.py      util.py

build/bdist.macosx-14.0-arm64/lib/pomodouroboros/model/test:
__init__.py         test_model.py       test_observables.py test_sessions.py    test_util.py

build/bdist.macosx-14.0-arm64/python3.13-standalone:
app

build/bdist.macosx-14.0-arm64/python3.13-standalone/app:
Frameworks  collect     lib-dynload temp

build/bdist.macosx-14.0-arm64/python3.13-standalone/app/Frameworks:

build/bdist.macosx-14.0-arm64/python3.13-standalone/app/collect:

build/bdist.macosx-14.0-arm64/python3.13-standalone/app/lib-dynload:

build/bdist.macosx-14.0-arm64/python3.13-standalone/app/temp:
```

There are symbolic links in `dist`, but nothing that links to `build`:

```
 /.../Pomodouroboros/dist/Pomodouroboros.app/Contents/MacOS/python -> /.../Pomodouroboros/.venv/bin/python
 /.../Pomodouroboros/dist/Pomodouroboros.app/Contents/Resources/icon.icns -> /.../Pomodouroboros/icon.icns
 /.../Pomodouroboros/dist/Pomodouroboros.app/Contents/Resources/lib/python3.13/config -> /.../Pomodouroboros/.venv/lib/python3.13/config
 /.../Pomodouroboros/dist/Pomodouroboros.app/Contents/Resources/lib/python3.13/site.pyc -> ../../site.pyc (broken link)
```

The binary itself does not appear to contain any string with build in the name:

```bash
$ rg --text build Pomodouroboros
41:NSAutoreleasePoolallocinit%@NSApplicationLoad() failedrelease/usr/lib/libobjc.dylibobjc_getClasssel_getUidobjc_msgSend/System/Library/Frameworks/Cocoa.framework/CocoaNSLogNSApplicationLoadNSRunAlertPanel/System/Library/Frameworks/ApplicationServices.framework/ApplicationServicesGetCurrentProcessSetFrontProcessLSOpenFSRefLSFindApplicationForInfoNSApplicationsharedApplicationactivateIgnoringOtherApps:The application could not be launched.%@ has encountered a fatal error, and will now terminate.TerminateOpen ConsoleConsole.appThe Info.plist file must have values for the CFBundleName or CFBundleExecutable strings.The Info.plist file must have a PyRuntimeLocations array containing string values for preferred Python runtime locations.  These strings should be "otool -L" style mach ids; "@executable_stub" and "~" prefixes will be translated accordingly.@executable_path/A Python runtime not could be located.  You may need to install a framework build of Python, or edit the PyRuntimeLocations array in this application's Info.plist file.EXECUTABLEPATHPython applications can not currently run from paths containing a '/' (or ':' from the Terminal).PyResourcePackagesPyOptionsuse_pythonpathPYTHONPATH:optimize%dHOMEPyMainFileNames__main__
See the Console for a detailed dyld error messageNSTaskNSPipepipesetLaunchPath:/bin/shsetStandardOutput:setArguments:launchwaitUntilExitfileHandleForReadingreadDataToEndOfFiletercomponentsSeparatedByString:componentsJoinedByString:
```

What other information can I provide?

**Comment by glyph** [comment]
So, following your steps exactly, I got the same error.  I'm not quite sure why, because I thought that `py2app` would have taken care of installing the local distribution for you, but try doing `pip installe -e .` after you install requirements.txt, and see if that gets you up and running.

My local venv automation always installs the "current package", (whatever is top-level in the directory I'm working in) via `pip install -e .` so I hadn't noticed this.

**Comment by pquentin** [comment]
Yes, `pip install --editable .` fixes the problem! I followed the README that does not currently suggest this:

https://github.com/glyph/Pomodouroboros/blob/f96f4fe42fe6391ab4fb2d0ce6e3c0a4252efa7c/README.md?plain=1#L78-L79
